// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtejtydkkregmkxicnyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0ZWp0eWRra3JlZ21reGljbnlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0MDMyMDYsImV4cCI6MjA4NTk3OTIwNn0.a-SaVGltz9lpmMLalpxHNmh8fVnSMwc8b_RuC0m7w4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});