// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhqjeyyphfoglehtmwod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpocWpleXlwaGZvZ2xlaHRtd29kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MjY0NzIsImV4cCI6MjA3MTIwMjQ3Mn0.yr29EcJR9jD0yzldWP9s93Fy7DGcTXWSZDgJDLY3weg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});